plot(x,sampleLoc1,x,sampleLoc2,x,sampleLoc3)
xlabel('Estimated Location')
ylabel('Sample Sets')
plot(D(x), estSampleSet1, D(x), estSampleSet2, D(x),estSampleSet3)
xlabel('Maximum Deviation')
ylabel('Estimated Sample Sets')
estCoefficients = log(estCoefficient1:estCoefficient7)
plot(estCoefficients, estSampleSet1, estCoefficients, estSampleSet2, estCoefficients, estSampleSet3)
xlabel('Estimated Coefficients')
ylabel('Estimated Sample Sets')
plot(D(x),x)
xlabel('Maximum Deviation')
ylabel('Estimated Location')